### PR TITLE
chore(Upgrade to Angular 5.2.0, Monaco 0.10.1, Electron 1.8.1)

### LINKED ISSUE #23: monaco-editor's page scroll  is not  showing
monaco-editor's page scroll - minimap  is not  showing  in the RHS top corner!
I think its available from .9.0 . you are using .8.0. 

[https://github.com/Microsoft/vscode/issues/4865](https://github.com/Microsoft/vscode/issues/4865)

### PR DESCRIPTION
**Pull request by jeremysmartt**
## Description
Upgrade to Angular 5.2.0, Monaco 0.10.1, Electron 1.8.1

closes #23 

#### Test Steps
- [ ] Checkout branch
- [ ] rm -rf node_modules
- [ ] npm i
- [ ] npm run build
- [ ] cd deploy/platform/code-editor
- [ ] npm pack (prints out a tgz file created)
- [ ] pwd (prints out your < path > you are at)
- [ ] Go to Covalent repo
- [ ] rm -rf node_modules/`@covalent`/code-editor
- [ ] npm install < path > / < tgz file created >
- [ ] npm run serve
- [ ] In browser go to: http://localhost:4200/#/components/code-editor
- [ ] See the Editor working

#### Test Steps on every PR
- [ ] `npm run test` passes
- [ ] `ng lint` passes

### CODE REVIEW

**Comment by emoralesb05** [comment]
Before jumping into 1.0.0.. I would want us to do an RC with `ng-packgr` as the build process, so we have the Angular Build format and also we need to update the `package.json` in the `platform/code-editor` dir to angular `^5.0.0`.

**Comment by jeremysmartt** [comment]
@emoralesb05 
"and also we need to update the package.json in the platform/code-editor dir to angular ^5.0.0"

Why 5.0.0 instead of 5.1.0?

**Comment by emoralesb05** [comment]
Because people might be on 5.0.0 and still use our module.. there is no reason in forcing an upgrade to 5.1.0 if we don't need anything in particular from 5.1.0 in this module.

We can still keep this repo on 5.1.0 to test and what not, but the `package.json` of the `platform/code-editor` module should be on `peerDependency of ^5.0.0`

**Comment by emoralesb05** [comment]
LGTM

**Review by emoralesb05 — APPROVED** [review]

**Pull request merged**
